### ISSUE TITLE
Working directory option

### ISSUE THREAD

**Issue by PaulMonnery** [julianwachholz/flake8-action#11]
Hi, thanks for your work on this action!

I have a monorepo with `front` and `back` directories at root.
Thanks to #5, I can run flake8 only on back, but the `.flake8` config file in this directory is not used. 

A workaround I found was to copy the file to `~/.config/flake8 (as explained [here](https://flake8.pycqa.org/en/latest/user/configuration.html#user-configuration)) but an option to specify the working directory would be really useful.

Thanks!

**Comment by julianwachholz** [comment]
Hi @PaulMonnery 
Thank you for your report. Would using [`--config`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-config) also be a possible solution?

**Comment by PaulMonnery** [comment]
I don't know how I managed to miss it, but yes, it does work too!
A `configPath` option would be nice. Another way to deal with it could be to add an `arg` option that forwards the given arguments, so we are free to specify the path to folder to lint, to config file, etc.

**Comment by julianwachholz** [comment]
This works now!

I created a test repository with an example: https://github.com/julianwachholz/flake8-action-test/commit/c635afcab297f7336b04071ed12b55a23033fb85
