### ISSUE TITLE
"No more than 50 items are allowed" error encountered

### ISSUE THREAD

**Issue by ReiFan49** [julianwachholz/flake8-action#17]
Linting annotation can't go more than 50 items. As I'm still testing on one of the repo, I hit a number somewhat more than 100 errors triggered by the linter (will fix that later).

I'm thinking about either:
- put one annotation for 51+ errors
- split the requests for every 50 annotation (fitting Github API limit)

either way should be able to inform the user since the errors are meant to be informative enough or something.

**Comment by julianwachholz** [comment]
Thank you for bringing this to my attention, I wasn't aware of this limitation until now. I will check which option would be better!
